#!/bin/sh
mvn clean package && docker build -t karan/msaclient01 .
docker rm -f msaclient01 2>/dev/null || true && docker run -it --name msaclient01 -p 8080:8080 -p 4848:4848 -p 8181:8181 --name msaclient01 karan/msaclient01
