#!/bin/sh
#deploy="false"
deploy="true"

image=msaclient01
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t karan/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push karan/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag karan/${image}:1.0-SNAPSHOT karan/${image}:latest
        docker push karan/${image}:latest
    fi
fi