# -*- coding: utf-8 -*-
"""SR25MSAD016.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1bcC5l9OZtmoaRyMKD7cbFa-SW3ahY9
"""

!pip install requests==2.32.5

!pip install -U langchain langchain-community faiss-cpu
!apt-get install zstd
!curl -fsSL https://ollama.com/install.sh | sh

import subprocess, time
subprocess.Popen(['ollama', 'serve'])
time.sleep(5)
print("Ollama Start")

!pip install ollama

!ollama pull llama3.2
!ollama pull mxbai-embed-large

!ollama list

documents = ["Shelf Discovery Tourism: Exploring local artisanal markets and specialty grocery stores for unique souvenirs. cost_rating:1, interest_socre: 92, Category: Cultural" ,
 "Urban Micro-Hiking: Using local green belts and hillocks for sunrise 'run-cations' followed by local breakfast. cost_rating:3, interest_socre: 85, Category: Fitness",
"Backyard Reading Retreat: Setting up a dedicated 'phone-free' zone with a library-loaned book list and DIY cold-brew station.. cost_rating:1, interest_socre: 78, Category: Relaxation",
"Swimming competion: Learn a new skill how to swim first time and first time win a swimming compation. cost_rating = 2, intrest_score:90, Category: Fitness"]

# generate embeddings:
from langchain_community.embeddings import OllamaEmbeddings

embeddings = OllamaEmbeddings(model="mxbai-embed-large")

# Vectore DB Create:
from langchain_community.vectorstores import FAISS

db = FAISS.from_texts(documents, embeddings)
db.save_local("my_vector_db")

# Load LLM:
from langchain_community.llms import Ollama
llm = Ollama(model="llama3.2")

# User Query:
query = input("Enter your question: ")

# similarity search:
context = db.similarity_search(query, k=3)
context

# Prompt:
prompt = """
  You are an expert vacation guide for local tourism.
You are professional in your work and highly skilled in recommending summer activities.
Your focus is to suggest activities that are low-cost and highly interesting.
Use the context provided below to generate your answer.

  context: {context}
  question: {query}
  answer:
"""

response = llm.invoke(prompt.format(context=context, query=query))
print(response)